name: Azure Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - uses: actions/checkout@v2

      # Set up Node.js environment with version 14
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      # Install dependencies
      - run: npm install

      # Install Angular CLI globally
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      # Linting: Check for code quality issues
      - name: Run ESLint
        run: npm run lint

      # Run Unit Tests in Chrome Headless mode
      - name: Run Unit Tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      # Build the project for production
      - name: Build the project
        run: npm run build --prod

      # Security audit: Check for vulnerabilities and fix them
      - name: Run security audit
        run: npm audit fix

      # Automatically check for Angular updates and apply them if necessary
      - name: Check for Angular updates
        run: ng update --all --force

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'BLOG-APP'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
